# Cores
COR_PRETO = (0, 0, 0)
COR_BRANCO = (255, 255, 255)
# largura e altura da bola
BALL_WIDTH = 16
BALL_HEIGHT = 16
# Largura, altura e outras métricas de tela
TELA_LARGURA = 1280
TELA_ALTURA = 720
TELA_CENTRO_X = TELA_LARGURA / 2
TELA_CENTRO_Y = TELA_ALTURA / 2
TELA_E_TERCO = TELA_LARGURA / 3
TELA_D_TERCO = TELA_E_TERCO * 2
TELA_MARGEM_ESQUERDA = 0
TELA_MARGEM_DIREITA = TELA_LARGURA - BALL_WIDTH
TELA_MARGEM_SUPERIOR = 0
TELA_MARGEM_INFERIOR = TELA_ALTURA - BALL_HEIGHT
